name: Feature request
about: Suggest a feature
title: "[Feature]:"
labels: ["enhancement"]
body:
  -type: markdown
   attributes:
     value: |
       Thanks for filling out this report to help us improve!
  -type: input
    id: Feature
    attributes:
      label: Feature description
      description: Describe the feature you'd like
      placeholder: Feature description
      validations:
        required: true
  -type: input
    id: Motivation
    attributes:
      label: Motivation
      description: Please enter the motivation for this feature i.e (problem, performance, etc)
  -type: input
    id: Possible Implementation
    attributes:
      label: Possible implementation
      description: Please enter any possible implementation for this feature
  -type: input
    id: Additional context
    attributes:
      label: Additional context
      description: Add any additional context about the feature request.
      placeholder: Additional context


