name: PyBOP

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pip nox
          pip install -e .
      - name: Test with nox
        run: |
          nox

  # Runs only on Ubuntu with Python 3.11
  check_coverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: Coverage tests (ubuntu-latest / Python 3.11)

    steps:
      - name: Check out PyBOP repository
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pip nox
          pip install -e .

      - name: Run unit tests for Ubuntu with Python 3.11 and generate coverage report
        run: nox -s coverage

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}